@extends('layouts.app')

@section('content')
@include('public.top-search')
<div class="about-page-area bg-secondary section-space-bottom page-margin">
  <div class="container panel" id="increase-margin-bottom">
    <h2 class="title-section" id="head-color">Privacy policy</h2>
    <div class="inner-page-details inner-page-padding">
      <div>

        <h2></h2>
<!--  <p class="about-us-border">
</p> -->

  <div>
    The reports provided by GarnerInsights.com are for internal use by the client and cannot be used for general publication or distribution to third parties. GarnerInsights.com is not responsible for the incorrect information, numbers or analysis received from report manufacturers.<br>
    Any further reproduction, photocopying, transmission in any form, recording or anything else should not be done without permission from the publisher.
    <br>
  </div>
  <br>
  <div>
    <h2 class="text-gray">The Information We Collect </h2>
    <div>
      When you visit this site, your IP address is recorded. We use your IP address to help diagnose problems with our server and to administer our website by creating statistical reports and tracking errors. Your IP address is used to help identify you when you buy and to gather broad demographic identification that will not be tied to your identity. 
      <br>
      If you select our feature to inform others about our site or about particular products on our site, we ask you for your name and email address and your colleague’s name and email address. GarnerInsights.com will automatically send the colleague a one-time email inviting them to visit the site. GarnerInsights.com does stores this information and is used for the sole purpose of sending emails and tracking the success of our referral program. 
      <br>
      We ask for personal information (1) when you subscribe to our Alert or newsletter services, (2) when you want to view detailed information about our products, (3) when you want to submit a question about our products/services to our customer service staff or (4) when you buy products. The types of personal information that may be collected on these pages are: name, company name, title, mailing address, e-mail address, phone number, fax number and credit card information. 
      <br>
      This site also uses "cookies", certain bits of information that are deposited on your computer when you visit this site and sent back to this site when you visit again. Cookies give us information about how many people visit certain pages on the site. We also use cookies so you don’t have to re-enter your login address or password each time you return to our site. In certain instances, we also use cookies to track the area of the site that you are on when you register as a user. If you do not have cookies enabled, you can still use our site, but you will have to log in each time you return to the site. 
      <br>
      This website uses Google Analytics, a web analytics service provided by Google, Inc. ("Google"). Google Analytics uses "cookies", which are text files placed on your computer, to help the website analyse how users use the site. The information generated by the cookie about your use of the website (including your IP address) will be transmitted to and stored by Google on servers in the United States.<br>
      Google will use this information for the purpose of evaluating your use of the website, compiling reports on website activity for website operators and providing other services relating to website activity and internet usage. Google may also transfer this information to third parties where required to do so by law, or where such third parties process the information on Google's behalf. <br>Google will not associate your IP address with any other data held by Google. You may refuse the use of cookies by selecting the appropriate settings on your browser, however please note that if you do this you may not be able to use the full functionality of this website. By using this website, you consent to the processing of data about you by Google in the manner and for the purposes set out above. 
      <br>
    </div>
    <br>
  </div>
  <div>
    <h2 class="text-gray"> How We Use Information?</h2>
    <div>
      We use your personal information to provide requested information and services to you and to help ensure that the information we provide to you is relevant to your specific needs. 
      <br>
      When you buy something, your information will be stored on our system to complete the buying process. It must be shared with an outside party in order to verify your credit card information. We also record information about your questions to us and your purchases so that we and you can keep track of what you've asked about or ordered directly on our site. Additionally, we may need to contact you about your questions and/or your orders. 
      <br>
      We use email addresses to send you the Alerts or newsletters you've requested, to answer the email we receive and to communicate with you about publications which you have told us you would be interested in hearing about. 
      <br>
    </div>
  </div>
  <div>
    <h2 class="text-gray">Other Parties' Collection and Use of Your Information </h2>
    <div>
      We do not share, sell, rent, or trade personal identifiable information with third parties for their promotional purposes. 
      <br>
      We do use agents, service providers and other third parties to provide some services on our site. These companies do not retain, share, store or use personally identifiable information for any other purposes then those described below: 
    </div>
    <div>
      <h3>Agents </h3>

      Publishers: 
      We may share your contact information with the publisher(s) whose reports you purchase. The publisher(s) may send you marketing materials. If you do not wish to receive these materials you will need to contact the publisher directly in order to opt-out (providing the publisher offers an opt-out). 
      <br>
      <h3>Service Providers </h3>

      <b>Shipping: </b>
      Our publishers use an outside shipping service provider to fulfil orders. These orders will be shipped to you directly from the publisher. In these cases, the publisher receives your contact information. 
      <br>
      <b>Credit Card Processing: </b>
      When you buy something with a credit card, we use a credit card processing service provider to verify your credit card and bill you. In addition, the name of your company (but not your name or contact information) will be shared with the publisher of the information you bought. 
      <br>
    </div>
    <div>
      <b>Other Third Parties </b><br>
      Tracking Service: <br>
      A third party tracking service provider may set cookies on our website to help us track to what extent sales are being generated from various marketing efforts. This information is only used in the aggregate. We do not link the information we store in cookies to any personally identifiable information you submit while on our site. 
      <br>
      Also, we may use a  third party tracking service employs a software technology like Clears Gifs, Web Beacons/Web Bugs, that help us better manage content on our site by informing us what content is effective. They are tiny graphics with a unique identifier, similar in function to cookies, and are used to track the online movements of website users. The main difference between the two is that clear gifs are invisible on the page and are much smaller, about the size of the period at the end of this sentence. Clear gifs are tied to users' personally identifiable information but may be used by GarnerInsights.com only to determine the effectiveness of various marketing programs. 
      <br>
    </div>
    <div>
      <h2 class="text-gray">Changes in this Privacy Statement </h2>
      <div>

        If we decide to change our privacy policy, we will post those changes to this privacy statement on the home page and other places we deem appropriate so that you are aware of what information we collect, how we use it, and under what circumstances, if any, we disclose it. 

        We reserve the right to modify this privacy statement at any time, so please review it frequently. If we make material changes to this policy, we will notify you here, by email, or by means of a notice on our home page. 

      </div>

      <h2 class="text-gray">Legal Disclaimer </h2>
      <div>
        We reserve the right to disclose your personally identifiable information as required by law and when we believe that disclosure is necessary to protect our rights and/or to comply with a judicial proceeding, court order, or legal process served on our website. 
      </div>
      <h2 class="text-gray">Security</h2>
      GarnerInsights.com is committed to protecting the security of your personal information. We use a variety of security technologies and procedures to help protect your personal information from unauthorized access, use, or disclosure. For example, we store the personal information you provide on computer systems with limited access that are located in controlled facilities.
    </div>
  </div>

</div>
</div>  
</div>  
</div> 
</body>
</html>
@endsection
